---
title: "Assignment"
description: |
  A short description of the post.
author:
  - name: Peirong LIN
    url: https://www.linkedin.com/in/perry-lin/
date: 07-13-2021
output:
  distill::distill_article:
    self_contained: false
---

# Visualizing 

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
  fig.retina=3,
  echo = TRUE,
  eval = TRUE,
  message = FALSE, 
  warning = FALSE)
```


```{r,echo=TRUE,eval=TRUE}
packages <- c('raster','sf','tmap','clock','tidyverse','data.table')
for (p in packages){
  if (!require(p,character.only = T)){
    install.packages(p)
  }
  library(p,character.only = T)
}
```

```{r}
bgmap <- raster("Geospatial/MC2-tourist.tif")
bgmap
```

```{r}
tmap_mode("plot")
tm_shape(bgmap) + 
  tm_raster(bgmap,
            legend.show = FALSE)
```

```{r}
tm_shape(bgmap) + 
tm_rgb(bgmap,r = 1, g = 2, b = 3,
       alpha = NA,
       saturation = 1,
       interpolate = TRUE,
       max.value = 255)
```

```{r}
Abila_st <- st_read(dsn = "Geospatial",
                    layer = "Abila")
```

```{r}
gps <- read_csv("gps.csv")
glimpse(gps)
```

```{r}
cc_data <- read_csv("cc_data.csv")
loyalty <- read_csv("loyalty_data.csv")
```

```{r}
gps$Timestamp <- date_time_parse(gps$Timestamp,
                                 zone = '',
                                 format = "%m/%d/%Y %H:%M:%S")
gps$day <- as.factor(get_day(gps$Timestamp))
gps$id <- as_factor(gps$id)
```

```{r}
cc_data %>%
    group_by(location) %>%
    summarise(count=n()) %>%
    arrange(count)
```


```{r}
cc_data %>%
    group_by(location) %>%
    summarise(count=n()) %>%
  ggplot(aes(x= location, y = count)) +
  geom_col()
```

```{r}
loyalty$loyaltynum <- ifelse(is.na(loyalty$loyaltynum), loyalty$price, loyalty$loyaltynum)
```

```{r}
loyalty <- loyalty %>% mutate(price = ifelse(price %like% 'L', 0, price))
```

```{r}
loyalty$price <- as.numeric(loyalty$price)
```

```{r}
cc_data$timestamp <- date_time_parse(cc_data$timestamp,
                                 zone = '',
                                 format = "%m/%d/%Y %H:%M")
cc_data$day <- as.factor(get_day(cc_data$timestamp))

loyalty$timestamp <- date_time_parse(loyalty$timestamp,
                                 zone = '',
                                 format = "%m/%d/%Y")
loyalty$day <- as.factor(get_day(loyalty$timestamp))
```

```{r}
comb <-merge(cc_data,loyalty, by=c("day","location","price"), all.x=TRUE, all.y=FALSE)
```



```{r eval=FALSE, include=FALSE}
gps1 <- gps %>%
  filter(Timestamp < "2014-01-06 23:59:00")
```

```{r}
gps_sf <- st_as_sf(gps,
                   coords = c("long","lat"),
                   crs = 4326)
```

```{r}
gps_path <- gps_sf %>%
  group_by(id,day) %>%
  summarize(m = mean(Timestamp),
            do_union = FALSE) %>%
  st_cast("LINESTRING")
```

```{r}
gps_path
```


```{r}
gps_path_selected <- gps_path %>%
  filter(id==1)
tmap_mode("view")
tm_shape(bgmap) +
  tm_rgb(bgmap, r = 1,g = 2,b = 3,
       alpha = NA,
       saturation = 1,
       interpolate = TRUE,
       max.value = 255) +
  tm_shape(gps_path_selected) +
  tm_lines()
```

